### ISSUE TITLE
Game crashes when using LoadImageSync

### ISSUE THREAD

**Issue by solaris783** [RaiaN/RuntimeImageLoader#36] opened 2024-01-30 00:29 UTC
>Assertion Failed: !bFlushing
>[File:...HTTP\Private\HttpManager.cpp] [Line: 397]

Also happens with LoadGif with Synchronous checked.

I bought the plugin in the unreal marketplace but because I am making a product from source code using UE 5.1, the unreal launcher couldn't find my project so I couldn't use the "Install to Project" button. So to make it work I downloaded the main branch from this github page into my project's engine Engine/Runtime folder, compiled the engine, then the project, added the plugin to the project, added the node (connected to the Runtime Image Loader subsystem), and ran the game in standalone mode.
Loading the link to the gif from the browser, outside of Unreal, works fine so I know it's not a problem with the image itself.
Loading Asynchronously works as expected.

**Comment by RaiaN** [comment] 2024-01-30 11:42
Can't reproduce the issue... Please send full logs. 
I also tried to use sync API in the standalone mode, no luck.

**Comment by RaiaN** [comment] 2024-03-06 19:53
Closing this issue as can't repro

**Closed by RaiaN** 2024-03-06 19:53 UTC
